{% set version = "2.1.1" %}

package:
  name: djangorestframework-csv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-csv/djangorestframework-csv-{{ version }}.tar.gz
  sha256: aa0ee4c894fe319c68e042b05c61dace43a9fb6e6872e1abe1724ca7ea4d15f7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - djangorestframework
    - six
    - unicodecsv

test:
  imports:
    - rest_framework_csv

about:
  home: https://github.com/mjumbewu/django-rest-framework-csv
  license: BSD
  summary: CSV Tools for Django REST Framework

extra:
  recipe-maintainers:
    - ocefpaf
