{% set version = "2.1.0" %}

package:
  name: djangorestframework-csv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-csv/djangorestframework-csv-{{ version }}.tar.gz
  sha256: 2f008b20a44f2d3c37835ea5b5ddfe19f54394f07b9cb267c616a917a7f7e27c

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - djangorestframework
    - six
    - unicodecsv

test:
  imports:
    - rest_framework_csv

about:
  home: https://github.com/mjumbewu/django-rest-framework-csv
  license: BSD
  summary: 'CSV Tools for Django REST Framework'

extra:
  recipe-maintainers:
    - ocefpaf
