travis:
  secure:
    BINSTAR_TOKEN: Asc8UNqH/+p5hGyTtBjuE1It6O4CrhX9KROiCFBql1VkoGPfTs/JxalJyNmHjzfrEb23/cpEitE6Z8ioVYLen+HaGqsR7mbxQ/wQvC0f6GH1X/SzR7AZA7ee8VUdVfXTKbE1daGvOHnIZsOQ+Q5R3e3jH3/b5eecrqHCpLtMQrkZdSHpIoMk7xMWpBHt+RytbLDHopU4EUU/lYfB/5hYm/YRErFYFII8Dxr6Ie2788+C6PaVMtyD3UL23TxmzMINuz0VyvQEJ0vTnIYx85EnYW90ShLOeX6ZBEyRZJ1J+agR2FU/BTX1ovqINLVjbpxxfFLb7qD+KfhwVZTWhLb0jaa9fiM/P07FTb5VJDvK6hDH4+Sl5laRwEPM3FnLXMKwOUQyhjckZcuQM3+pXISu/Qrv4pdiaAnPH/P6AQ/v/x5NCVGFP3fhxutCR77D65FZt1g0B3736GLyXyvibSGJ4ulAgUXDp1h538iVrhSnOOel1qp8/svi6TvGO0PQofYjrxjLY509UHMgJNF3ZDK6IhvrOcvj2mji5sY3ZBugGSN38WpjvkVRIJmd3cK348M/ji84Ra7tzoXQGpnoWDfIMFG44SUeEKk37Pqcf8+1F9O3XXr+4BB1YyKL6POywUDSUGIJ0symCRWD6QJi6WUiDT7uNd9WI2hjFitwnc8cGzw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
