travis:
  secure:
    BINSTAR_TOKEN: NFbXjVEW2+Guqz2ixeKryRF2Y6t1pFWNEMKOm0sj01LVcm33WaDJJrM+Bk8R8kpzeZrA8CXFPfES+nRyQQMt7RD2BBjsFztum5anOkNODu0LiNLNb5F5Tx4GTya69ru2+8xxmgJ0hOjGVpY7W9PiRaWG4iB75CounKYeXWmGuvLDDRYCD3Hm2ygK4W4m2aJyHT0YZr/1jGDqHcmR+JAMeWzbmaNyRei5BgjWUo8U74y9UI1fabWPcuPt+/XZPSh5fReW7+RHKD//MAmpcy7LUR67sqGv8+cpRlHfiCoXbHuevYxpxkbe6U09AXPSS/RD6LWdslqOGQJP6F9Rr+wqyCvxUgG+AVouNjx6dUO2VtoI1KQU+2JlO2RzLZuiP6TWnc7zAwHyctYbgooxeouNMSvWfr2cVzlH4M2wOy9MfI8+OYV/NC+1wbowYL58ztm6wdGeFkREiyUpXRrT5HOHKc7ukhUewDUlktcPxNl9lXHvhmlD9J1GkOi8vg5lxWX3AF/blRfVILj6fTyOyzVZ4l/hqItrMk3GvJnb2V7AZaUs5EjegDXdUfYz+gnoSVBFOsf1fdWJz1PFDkLTP2d618iUdPVr+HhgcceV1271ZPPJ5UsgcvFS4kzDMJHcdr3ZuULeVHNMe2aBBDsFKP3kXPZ7VV9yAQgFzTmzFwvQWig=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
